routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@front')->name('front');

Route::group(['prefix' => 'api'], function () {
    Route::resource('/hotdogs', 'HotDogController')->except(['show', 'create', 'edit']);
});

app/Models/Hotdog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Hotdog extends Model
{
    protected $fillable = ['title', 'image_number'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HotDogController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\Hotdog as HotDogResource;
use App\Models\Hotdog;
use Illuminate\Http\Request;

class HotDogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index()
    {
        return HotDogResource::collection(Hotdog::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $hotdog = Hotdog::create($request->all());

        return response()->json($hotdog, 201);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Hotdog $hotdog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Hotdog $hotdog)
    {
        $hotdog->update($request->all());

        return response()->json($hotdog, 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Hotdog $hotdog
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy(Hotdog $hotdog)
    {
        $hotdog->delete();

        return response()->json(null, 204);
    }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

class PagesController
{
    public function front()
    {
        return view('pages.front');
    }
}

resources/views/includes/footer.blade.php
<footer class="footer">
    <div class="container">
        <p class="credits">Hot dog's REST API, by <a href="mailto:itwasntluck@gmail.com">EXayer</a>, 2019.</p>
    </div>
</footer>

resources/views/includes/header.blade.php
<header class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ route('front') }}">Hot dog REST API</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar"
                    aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('hotdogs.index') }}">GET Hot dogs</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

resources/views/includes/hotdog-template.blade.php
<script type="text/template" id="hotdog-template">
    <div class='hotdog-instance' data-id='<%= id %>'>
        <h6><strong><%= title %></strong></h6>
        <div>
           <img src="<%= image %>" alt="HotDog" width="150" height="150" data-number="<%= number %>">
        </div>
    </div>
</script>

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <meta name="description" content="">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
</head>
<body>
@include('includes.header')
<main role="main">
    @yield('content')
    @include('includes.hotdog-template')
</main>
@include('includes.footer')
<script src="{{ mix('js/app.js') }}"></script>
</body>
</html>

resources/views/pages/front.blade.php
@extends('layouts.main')
@section('title', 'Hot Dogs | REST API')

@section('content')
    <div class="container">
        <h1 class="text-center my-3 text-info">Hot dogs</h1>
        <div class="row">
            <div class="col-12 col-lg-11">
                <form method="POST" action="{{ route('hotdogs.store') }}" class="create-edit-form">
                    <input type="hidden" name="id" value="">
                    <div class="form-row align-items-end">
                        <div class="col-sm-5 my-1">
                            <label for="title">Title</label>
                            <input type="text" class="form-control" id="title" name="title"
                                   placeholder="Hotdog title" required maxlength="80">
                        </div>
                        <div class="col-sm-5 my-1">
                            <label class="mr-sm-2" for="image_selector">Image</label>
                            <select class="custom-select mr-sm-2" id="image_selector" name="image_number" required>
                                <option selected value="1">Image #1</option>
                                <option value="2">Image #2</option>
                                <option value="3">Image #3</option>
                            </select>
                        </div>
                        <div class="col-12 col-sm-auto my-1 submit">
                            <button type="submit" class="btn btn-primary submit-btn">Create</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-12 col-lg-1 d-flex align-items-end">
                <form method="POST" action="{{ route('hotdogs.destroy', 0) }}" class="delete-form">
                    <input type="hidden" name="id" value="">
                    <div class="form-row align-items-end">
                        <div class="col-12 my-1">
                            <button type="submit" class="btn btn-danger submit-btn" disabled>Delete</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-12">
                <hr>
                <div class="d-flex justify-content-between text-info">
                    <span>Click to select a hot dog</span>
                    <span>Total: <span id="hotdog-counter">0</span></span>
                </div>
            </div>

            <div class="col-12">
               <div id="hotdog-container" class="d-flex justify-content-center align-items-center flex-wrap">
               </div>
            </div>
        </div>
    </div>
@endsection